// ExampleComponent.js
import React, { useContext } from 'react';
import ThemeContext from './ThemeContext'

const ExampleComponent = () => {
  const { theme, toggleTheme } = useContext(ThemeContext);

  return (
    <div style={{ background: theme === 'light' ? '#fff' : '#333', color: theme === 'light' ? '#333' : '#fff' }}>
      <div className="header">
      <input type="text" />
      <p>Current Theme: {theme}</p>
      <button onClick={toggleTheme}>Toggle Theme</button></div>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia debitis magnam doloremque exercitationem illum sed et optio sint quo atque deserunt pariatur doloribus quas, eaque aliquam architecto incidunt consectetur totam. Nisi, qui sit? Inventore cupiditate, quisquam alias voluptatum magni fugit voluptatibus voluptatem dicta quaerat illo aliquam et exercitationem magnam illum vero, eos in possimus. Iure odio, quaerat sint vitae animi id tempora error similique non? Corrupti quaerat eius nihil animi, velit sunt facilis perferendis esse facere dolor possimus blanditiis. Saepe soluta commodi obcaecati perferendis cupiditate harum ut et sapiente nesciunt nulla, recusandae doloribus dolor officiis enim laboriosam fugit dignissimos? Nulla dolorem quisquam fuga quod nemo vero nobis reiciendis aspernatur optio dicta commodi accusamus, officia placeat explicabo, aliquid similique eligendi odio reprehenderit itaque tempore! Eligendi, officia! Delectus quaerat culpa voluptate dolore quidem suscipit. Saepe ipsa facere autem. Vel, molestiae doloribus itaque harum mollitia quo ipsam nam voluptas quidem eum in, provident voluptatibus molestias enim. A, dolorem eveniet? Qui nostrum mollitia ab quos. Ab sunt placeat dolores officiis incidunt neque soluta repellendus distinctio sint illo. Eveniet, rerum, quasi fugit cupiditate ut commodi error numquam consectetur, delectus voluptatum dolor similique ipsa inventore maxime totam earum sapiente fugiat natus itaque! Autem vero saepe, iure optio similique sint, doloribus consequatur perferendis culpa quisquam voluptate tempora repudiandae cupiditate, itaque consequuntur nulla inventore error officia quidem perspiciatis eius facere praesentium! Aperiam, consequatur, minima perspiciatis, similique repellat rerum quibusdam veritatis voluptates officia aliquam ipsa autem. Quidem praesentium modi, excepturi possimus aperiam tempora veniam quisquam, reprehenderit dolorum voluptatem placeat consectetur illum ratione quo obcaecati aspernatur distinctio ut optio corrupti provident eligendi accusamus vero facere sunt. Id atque, nisi tempora adipisci a dignissimos. Obcaecati soluta culpa quis laboriosam iure facilis recusandae. Similique quibusdam, magnam illo consequuntur neque assumenda incidunt. Amet voluptas nesciunt temporibus? Ducimus fugiat reprehenderit corrupti, rem natus dignissimos.</p>
     <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus fugiat aspernatur similique sit perspiciatis? Quo neque quidem iure alias et dicta quas maxime voluptas placeat qui eius, molestias, doloribus architecto.</p>
<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Et similique quis nisi magnam magni adipisci dignissimos. Mollitia hic debitis perspiciatis saepe vitae, iusto facilis cupiditate impedit illum eos laborum laudantium quos maxime labore tenetur illo aliquam repellat ipsum ipsam corrupti unde inventore fugiat. Reprehenderit alias repudiandae dolores obcaecati culpa hic maiores commodi at nihil, sequi debitis consequatur quas, rem eum. Quo, saepe ad. Incidunt numquam obcaecati, exercitationem ducimus minima odit vitae voluptates at culpa laudantium id delectus porro nemo architecto quos cum doloribus reprehenderit. Optio laborum ipsum corporis. A earum odit tempora at commodi et quidem quod, tempore consequuntur, molestiae velit eveniet est voluptatem quia minima. Ullam atque tempora exercitationem aspernatur repellat quod velit, eligendi voluptates nihil ad, eveniet animi mollitia, consequatur voluptas laborum sit natus. Cum magni nesciunt placeat et provident voluptatem nulla voluptatum, iure ullam fugiat temporibus commodi rem enim ut, fuga beatae harum. Blanditiis sapiente tempora quos, quisquam accusamus corporis minus facilis, odio nisi dicta eligendi expedita iusto consequatur nobis nihil, libero ducimus in? Vero provident eligendi delectus, consectetur maiores distinctio possimus expedita numquam? Aliquam commodi magnam maiores fugiat esse veniam impedit optio unde ipsum! Eius, ad. Accusantium officia praesentium eos dolorum doloremque, suscipit quibusdam saepe ipsa quos perferendis nihil aspernatur vel alias ea culpa cupiditate qui laudantium, beatae ad odio cum nisi quis ut neque. Saepe hic optio quia neque eum perferendis veniam est ad minus suscipit laudantium quis accusantium quas maiores cum enim perspiciatis animi, ea odio molestias. Minima, eius ipsam, atque laboriosam cumque eum harum excepturi laborum voluptatum fugit architecto a sit. Voluptatum voluptates corrupti iste esse soluta possimus similique cum laboriosam. Qui rem, nisi ab distinctio maxime quia libero est laboriosam cupiditate ipsam incidunt adipisci dolorem pariatur impedit mollitia dicta molestias vel doloribus. Sequi delectus quos itaque voluptatem reiciendis, officiis exercitationem. Possimus, natus.</p>
    </div>
  );
};

export default ExampleComponent;
